### ISSUE TITLE
Clarification about SK.ee & OCSP

### ISSUE THREAD

**Issue by tauntz** [konstantint/eid-webauth-samples#1]
README:

>  The main drawback is that the SK.ee OCSP service is not free and requires a contract.

The [official webpage](https://www.sk.ee/en/services/validity-confirmation-services/auth-ocsp/) about OCSP says:

> Prices
> The service is in pilot use and it is available free of charge. If you would like to register as a pilot user, send your request to sales[A]sk.ee.

No idea for how long this free offer lasts for but at the moment at least it seems to be free.

**Comment by konstantint** [comment]
True, although as far as I understood it will become a paid service eventually.
I fixed the text a bit.
